title: With Open Brackets
author: John Dorlus
email: email@powercoder.tech
description: > # this means to ignore newlines until "show_exerpts:"
  I am a JS Test Engineer/Software Engineer working remotely for large
  open source companies specializing in test automation, front end development and 
  quality assurance. This blog contains articles from my experiences. 
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: John Dorlus
  tagline: Sr. Software Engineer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: the_power_coder
    github:  cuff-links
    linkedIn: in/johndorlus
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed